toggle
js-tasks-ru/htmlcss-20220811_sergey-shmidt pull request #19
Opened 2022-09-04 20:29 UTC by schmidtsv55

2022-09-04 20:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-04 21:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-04 21:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-04 21:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-05 15:47 UTC, GSemikozov requested changes

2022-09-05 15:47 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    right: 50%;
слева надежнее в пикселях, и тогда перемещение сделать через transform: translateX тоже в пикселях

2022-09-06 19:44 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-07 15:52 UTC, GSemikozov requested changes

2022-09-07 15:52 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +    transform: translateY(-12px);
`left: 1px; transform: translateY(-50%);`
а ниже, когда меняем состояние, просто - 
`transform: translateX(/нужное значение/);`

2022-09-12 05:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-13 22:44 UTC, GSemikozov approved these changes

2022-09-13 22:44 UTC, merged