histogram
js-tasks-ru/htmlcss-20220811_sergey-shmidt pull request #6
Opened 2022-08-21 23:12 UTC by schmidtsv55

2022-08-21 23:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-22 09:23 UTC, GSemikozov requested changes

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 24px;
сверху 16

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
justify-content и align-content здесь лишние

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 26px;
39?

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-top: 10px;
3?

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-items: baseline;
flex-end

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-between;
лишнее

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    gap: 2px;
1

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    height: 60px;
50

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin: 0;
margin-top: 39px

2022-08-22 09:23 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +        <ul class="histogram">
списком верстать не надо, но - можем и оставить

2022-08-22 16:00 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-22 17:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-23 18:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-23 20:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-08-24 14:30 UTC, GSemikozov requested changes

2022-08-24 14:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram {
отдельный блок .histogram рядом с .chart? блок только 1, остальное - элементы, и надо решить как называется блок)
судя по смыслу, это .chart__histogram

2022-08-24 14:30 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__column {
тоже исправить

2022-08-25 12:04 UTC, GSemikozov approved these changes

2022-08-25 12:04 UTC, merged