main page layout
js-tasks-ru/htmlcss-20220811_sergey-shmidt pull request #8
Opened 2022-08-27 14:00 UTC by schmidtsv55

2022-08-27 14:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-30 17:10 UTC, GSemikozov requested changes

2022-08-30 17:10 UTC, GSemikozov commented on components/card/card.css
> +    box-sizing: border-box;
общие паддинги лучше сразу указать здесь, чтобы не задавать отдельно каждому ближайшему дочернему элементу

2022-08-30 17:10 UTC, GSemikozov commented on components/footer/footer.css
> +    margin-top: 32px;
margin: 32px auto 0

2022-08-30 17:10 UTC, GSemikozov commented on components/header/header.css
> +    flex-basis: 1110px;
лишнее

2022-08-30 17:10 UTC, GSemikozov commented on components/page/page.css
> +    flex-basis: 237px;
лишнее

2022-08-30 17:10 UTC, GSemikozov commented on components/page/page.css
> +    flex-basis: 384px;
лишнее

2022-08-30 17:10 UTC, GSemikozov commented on components/preview/preview.css
> +    flex-basis: 1110px
лишнее - везде где это надо, лучше использовать .container (как на лекции)

2022-09-01 15:43 UTC, GSemikozov approved these changes

2022-09-01 15:43 UTC, merged