tooltip
js-tasks-ru/htmlcss-20220811_sergey-shmidt pull request #9
Opened 2022-08-27 15:58 UTC by schmidtsv55

2022-08-27 15:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-08-30 17:05 UTC, GSemikozov requested changes

2022-08-30 17:05 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +body{
глобальные или вспомогательные стили не относящиеся к компоненту оформляем либо в глобальных файлах, либо (если нужны только для примера на данной странице) - прямо в теге style на хтмл странице

2022-08-31 21:08 UTC, GSemikozov approved these changes

2022-08-31 21:08 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-08-31 21:09 UTC, GSemikozov approved these changes

2022-08-31 21:09 UTC, merged